//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.4084.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pointcloud.org/schemas/PC/1.1")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://pointcloud.org/schemas/PC/1.1", IsNullable=false)]
public partial class PointCloudSchema {
    
    private dimensionType[] dimensionField;
    
    private object metadataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dimension")]
    public dimensionType[] dimension {
        get {
            return this.dimensionField;
        }
        set {
            this.dimensionField = value;
        }
    }
    
    /// <remarks/>
    public object metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pointcloud.org/schemas/PC/1.1")]
public partial class dimensionType {
    
    private string positionField;
    
    private string sizeField;
    
    private string nameField;
    
    private string descriptionField;
    
    private bool activeField;
    
    private bool activeFieldSpecified;
    
    private interpretationType interpretationField;
    
    private bool interpretationFieldSpecified;
    
    private rangeType minimumField;
    
    private rangeType maximumField;
    
    private double offsetField;
    
    private bool offsetFieldSpecified;
    
    private double scaleField;
    
    private bool scaleFieldSpecified;
    
    private endiannessType endiannessField;
    
    private bool endiannessFieldSpecified;
    
    private string uuidField;
    
    private string parent_uuidField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public bool active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool activeSpecified {
        get {
            return this.activeFieldSpecified;
        }
        set {
            this.activeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public interpretationType interpretation {
        get {
            return this.interpretationField;
        }
        set {
            this.interpretationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool interpretationSpecified {
        get {
            return this.interpretationFieldSpecified;
        }
        set {
            this.interpretationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public rangeType minimum {
        get {
            return this.minimumField;
        }
        set {
            this.minimumField = value;
        }
    }
    
    /// <remarks/>
    public rangeType maximum {
        get {
            return this.maximumField;
        }
        set {
            this.maximumField = value;
        }
    }
    
    /// <remarks/>
    public double offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool offsetSpecified {
        get {
            return this.offsetFieldSpecified;
        }
        set {
            this.offsetFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public double scale {
        get {
            return this.scaleField;
        }
        set {
            this.scaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool scaleSpecified {
        get {
            return this.scaleFieldSpecified;
        }
        set {
            this.scaleFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public endiannessType endianness {
        get {
            return this.endiannessField;
        }
        set {
            this.endiannessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool endiannessSpecified {
        get {
            return this.endiannessFieldSpecified;
        }
        set {
            this.endiannessFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string uuid {
        get {
            return this.uuidField;
        }
        set {
            this.uuidField = value;
        }
    }
    
    /// <remarks/>
    public string parent_uuid {
        get {
            return this.parent_uuidField;
        }
        set {
            this.parent_uuidField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pointcloud.org/schemas/PC/1.1")]
public enum interpretationType {
    
    /// <remarks/>
    int8_t,
    
    /// <remarks/>
    uint8_t,
    
    /// <remarks/>
    int16_t,
    
    /// <remarks/>
    uint16_t,
    
    /// <remarks/>
    int32_t,
    
    /// <remarks/>
    uint32_t,
    
    /// <remarks/>
    int64_t,
    
    /// <remarks/>
    uint64_t,
    
    /// <remarks/>
    @double,
    
    /// <remarks/>
    @float,
    
    /// <remarks/>
    unknown,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pointcloud.org/schemas/PC/1.1")]
public partial class rangeType {
    
    private interpretationType unitsField;
    
    private bool unitsFieldSpecified;
    
    private decimal valueField;
    
    private bool valueFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public interpretationType units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool unitsSpecified {
        get {
            return this.unitsFieldSpecified;
        }
        set {
            this.unitsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool valueSpecified {
        get {
            return this.valueFieldSpecified;
        }
        set {
            this.valueFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.4084.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pointcloud.org/schemas/PC/1.1")]
public enum endiannessType {
    
    /// <remarks/>
    big,
    
    /// <remarks/>
    little,
}
