version: '3.4'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    restart: always
#    volumes:
#       - ./infrastructure/database/data:/data
#       - ./infrastructure/database/extensions.sql:/docker-entrypoint-initdb.d/001_extensions.sql
#       - ./infrastructure/database/schema.sql:/docker-entrypoint-initdb.d/002_schema.sql
#       - ./infrastructure/database/alter_table.sql:/docker-entrypoint-initdb.d/003_alter_table.sql
#       - ./infrastructure/database/functions.sql:/docker-entrypoint-initdb.d/004_functions.sql 
#       #- ./infrastructure/database/data.sql:/docker-entrypoint-initdb.d/005_data.sql 
    environment:
#      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: joe
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: db_test
    ports:
      - "5432:5432"

  database_administration:
    image: dpage/pgadmin4
    container_name: database_administration
    #restart: always
    volumes:
      - ./database_administration/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_DEFAULT_EMAIL: nicky@santoro.great
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8080:8080"
